openapi: 3.0.0
info:
    description: This is a simple API
    version: "1.0.0"
    title: Simple Inventory API
    contact:
        email: you@your-company.com
    license:
        name: Apache 2.0
        url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
    /homes:
        get:
            tags:
                - Home
            summary: getHomes
            operationId: getHomes
            parameters:
                - $ref: '#/components/parameters/Filter'
                - $ref: '#/components/parameters/Search'
                - $ref: '#/components/parameters/Page'
                - $ref: '#/components/parameters/PageSize'
                - $ref: '#/components/parameters/Sort'
            responses:
                200:
                    description: List Home Response
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Home'
                        application/xml:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Home'
                400:
                    $ref: "#/components/responses/BadRequestException"
                401:
                    $ref: "#/components/responses/NotAuthorizedException"
                403:
                    $ref: "#/components/responses/ForbiddenException"
                404:
                    $ref: "#/components/responses/NotFoundException"
                405:
                    $ref: "#/components/responses/NotAllowedException"
                406:
                    $ref: "#/components/responses/NotAcceptableException"
                415:
                    $ref: "#/components/responses/NotSupportedException"
                500:
                    $ref: "#/components/responses/InternalServerErrorException"
                503:
                    $ref: "#/components/responses/ServiceUnavailableException"
        post:
            tags:
                - Home
            summary: addHome
            operationId: addHome
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/HomeReq'
                    application/xml:
                        schema:
                            $ref: '#/components/schemas/HomeReq'
            responses:
                200:
                    description: Home Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Home'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/Home'
                400:
                    $ref: "#/components/responses/BadRequestException"
                401:
                    $ref: "#/components/responses/NotAuthorizedException"
                403:
                    $ref: "#/components/responses/ForbiddenException"
                404:
                    $ref: "#/components/responses/NotFoundException"
                405:
                    $ref: "#/components/responses/NotAllowedException"
                406:
                    $ref: "#/components/responses/NotAcceptableException"
                415:
                    $ref: "#/components/responses/NotSupportedException"
                500:
                    $ref: "#/components/responses/InternalServerErrorException"
                503:
                    $ref: "#/components/responses/ServiceUnavailableException"

    /homes/{homeId}:
        get:
            tags:
                - Home
            summary: getHomeByHomeId
            operationId: getHomeByHomeId
            parameters:
                - $ref: '#/components/parameters/HomeId'
            responses:
                200:
                    description: 'asdasdas'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Home'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/Home'
                400:
                    $ref: "#/components/responses/BadRequestException"
                401:
                    $ref: "#/components/responses/NotAuthorizedException"
                403:
                    $ref: "#/components/responses/ForbiddenException"
                404:
                    $ref: "#/components/responses/NotFoundException"
                405:
                    $ref: "#/components/responses/NotAllowedException"
                406:
                    $ref: "#/components/responses/NotAcceptableException"
                415:
                    $ref: "#/components/responses/NotSupportedException"
                500:
                    $ref: "#/components/responses/InternalServerErrorException"
                503:
                    $ref: "#/components/responses/ServiceUnavailableException"
        put:
            tags:
                - Home
            summary: updateHomeByHomeId
            operationId: updateHomeByHomeId
            parameters:
                - $ref: '#/components/parameters/HomeId'
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/HomeReq'
                    application/xml:
                        schema:
                            $ref: '#/components/schemas/HomeReq'
            responses:
                200:
                    description: Home Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Home'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/Home'
                400:
                    $ref: "#/components/responses/BadRequestException"
                401:
                    $ref: "#/components/responses/NotAuthorizedException"
                403:
                    $ref: "#/components/responses/ForbiddenException"
                404:
                    $ref: "#/components/responses/NotFoundException"
                405:
                    $ref: "#/components/responses/NotAllowedException"
                406:
                    $ref: "#/components/responses/NotAcceptableException"
                415:
                    $ref: "#/components/responses/NotSupportedException"
                500:
                    $ref: "#/components/responses/InternalServerErrorException"
                503:
                    $ref: "#/components/responses/ServiceUnavailableException"
        delete:
            tags:
                - Home
            summary: deleteHomeByHomeId
            operationId: deleteHomeByHomeId
            parameters:
                - $ref: '#/components/parameters/HomeId'
            responses:
                204:
                    description: No Content
                    content:
                        application/json: {}
                        application/xml: {}
                400:
                    $ref: "#/components/responses/BadRequestException"
                401:
                    $ref: "#/components/responses/NotAuthorizedException"
                403:
                    $ref: "#/components/responses/ForbiddenException"
                404:
                    $ref: "#/components/responses/NotFoundException"
                405:
                    $ref: "#/components/responses/NotAllowedException"
                406:
                    $ref: "#/components/responses/NotAcceptableException"
                415:
                    $ref: "#/components/responses/NotSupportedException"
                500:
                    $ref: "#/components/responses/InternalServerErrorException"
                503:
                    $ref: "#/components/responses/ServiceUnavailableException"



components:
    schemas:
        Home:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                    example: 12
                address:
                    type: string
                    example: 'Hữu Hòa, Thanh Trì, Hà Nội'
                floor:
                    type: integer
                    example: 3
                square:
                    type: number
                    format: float
                    example: 36.6
                room:
                    type: integer
                    example: 5
                color:
                    type: string
                    example: 'Đỏ'
                owner:
                    type: string
                    example: 'Nguyễn Văn Hoàng'
        Homes:
            type: array
            items:
                $ref: '#/components/schemas/Home'
        HomeReq:
            type: object
            required:
                - address
                - floor
                - square
                - room
                - color
                - owner
            properties:
                address:
                    type: string
                    example: 'Hữu Hòa, Thanh Trì, Hà Nội'
                floor:
                    type: integer
                    example: 3
                square:
                    type: number
                    format: float
                    example: 36.6
                room:
                    type: integer
                    example: 5
                color:
                    type: string
                    example: 'Đỏ'
                owner:
                    type: string
                    example: 'Nguyễn Văn Hoàng'
        Error:
            type: object
            properties:
                status:
                    format: int64
                    readOnly: true
                    type: integer
                    example: 401
                code:
                    type: string
                    example: DOGOO-100
                message:
                    type: string
                developerMessage:
                    type: string
            required:
                - code
                - message

    responses:
        HomeRes:
            description: Home Response
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Home'
                application/xml:
                    schema:
                        $ref: '#/components/schemas/Home'
        HomesRes:
            description: List Home Response
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Homes'
                application/xml:
                    schema:
                        $ref: '#/components/schemas/Homes'

        BadRequestException:
            description: Request body not meet require
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
                application/xml:
                    schema:
                        $ref: "#/components/schemas/Error"
        NotAuthorizedException:
            description: Authentication failure
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
                application/xml:
                    schema:
                        $ref: "#/components/schemas/Error"
        ForbiddenException:
            description: Not permitted to access
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
                application/xml:
                    schema:
                        $ref: "#/components/schemas/Error"
        NotFoundException:
            description: The specified resource was not found
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
                application/xml:
                    schema:
                        $ref: "#/components/schemas/Error"
        NotAllowedException:
            description: HTTP method not supported
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
                application/xml:
                    schema:
                        $ref: "#/components/schemas/Error"
        NotAcceptableException:
            description: Client media type requested not supported
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
                application/xml:
                    schema:
                        $ref: "#/components/schemas/Error"
        NotSupportedException:
            description: Client posted media type not supported
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
                application/xml:
                    schema:
                        $ref: "#/components/schemas/Error"
        InternalServerErrorException:
            description: Internal Server Error
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
                application/xml:
                    schema:
                        $ref: "#/components/schemas/Error"
        ServiceUnavailableException:
            description: Server is temporarily unavailable or busy
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
                application/xml:
                    schema:
                        $ref: "#/components/schemas/Error"

    parameters:
        ApiKey:
            name: apikey
            in: header
            required: true
            schema:
                type: string
        HomeId:
            name: homeId
            in: path
            required: true
            description: Home Id
            schema:
                type: integer
                format: int64
        Search:
            name: search
            in: query
            required: false
            schema:
                type: string
        Filter:
            name: filter
            in: query
            required: false
            schema:
                type: string
        Sort:
            name: sort
            in: query
            required: false
            schema:
                type: string
        Page:
            name: page
            in: query
            required: false
            schema:
                type: integer
        PageSize:
            name: pageSize
            in: query
            required: false
            schema:
                type: integer